"""empty message

Revision ID: 183da19b57d1
Revises: 2a7575fc0fa7
Create Date: 2015-04-26 18:13:16.255680

"""

# revision identifiers, used by Alembic.
revision = '183da19b57d1'
down_revision = '2a7575fc0fa7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decisionType', sa.String(), nullable=True),
    sa.Column('option', sa.String(), nullable=True),
    sa.Column('sadPref', sa.Integer(), nullable=True),
    sa.Column('happyPref', sa.Integer(), nullable=True),
    sa.Column('angryPref', sa.Integer(), nullable=True),
    sa.Column('excitedPref', sa.Integer(), nullable=True),
    sa.Column('tiredPref', sa.Integer(), nullable=True),
    sa.Column('boredPref', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    ### end Alembic commands ###
