"""empty message

Revision ID: 4105876477d4
Revises: a83a18808f2
Create Date: 2015-05-02 23:48:31.501012

"""

# revision identifiers, used by Alembic.
revision = '4105876477d4'
down_revision = 'a83a18808f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
