"""empty message

Revision ID: ae025575696
Revises: 183da19b57d1
Create Date: 2015-04-30 19:57:58.368603

"""

# revision identifiers, used by Alembic.
revision = 'ae025575696'
down_revision = '183da19b57d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('angrypref', sa.Integer(), nullable=True))
    op.add_column('preferences', sa.Column('boredpref', sa.Integer(), nullable=True))
    op.add_column('preferences', sa.Column('decisiontype', sa.String(), nullable=True))
    op.add_column('preferences', sa.Column('excitedpref', sa.Integer(), nullable=True))
    op.add_column('preferences', sa.Column('happypref', sa.Integer(), nullable=True))
    op.add_column('preferences', sa.Column('sadpref', sa.Integer(), nullable=True))
    op.add_column('preferences', sa.Column('tiredpref', sa.Integer(), nullable=True))
    op.drop_column('preferences', 'sadPref')
    op.drop_column('preferences', 'boredPref')
    op.drop_column('preferences', 'tiredPref')
    op.drop_column('preferences', 'angryPref')
    op.drop_column('preferences', 'happyPref')
    op.drop_column('preferences', 'excitedPref')
    op.drop_column('preferences', 'decisionType')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('decisionType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('preferences', sa.Column('excitedPref', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('preferences', sa.Column('happyPref', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('preferences', sa.Column('angryPref', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('preferences', sa.Column('tiredPref', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('preferences', sa.Column('boredPref', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('preferences', sa.Column('sadPref', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('preferences', 'tiredpref')
    op.drop_column('preferences', 'sadpref')
    op.drop_column('preferences', 'happypref')
    op.drop_column('preferences', 'excitedpref')
    op.drop_column('preferences', 'decisiontype')
    op.drop_column('preferences', 'boredpref')
    op.drop_column('preferences', 'angrypref')
    ### end Alembic commands ###
